name: Create Archive
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'dev.zip'
        exclusions: '*.git* README.md *.schema* *.zip'
    - name: Delete dev files 
      run: rm assets/minecraft/textures/particle/dev/effect_*
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'patreon.zip'
        exclusions: '*.git* README.md *.schema* *.zip'
    - name: Delete
      uses: ame-yu/action-delete-latest-release@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "patreon.zip,dev.zip"
        tag: "patreon"
        token: ${{ secrets.GITHUB_TOKEN }}
