name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'patreon.zip'
        exclusions: '*.git* README.md'
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "patreon.zip"
        tag: "patreon"
        commit: "master"
        token: ${{ secrets.GITHUB_TOKEN }}
