name: Pull request workflow
on:
  pull_request:
    branches:
      - master
jobs:
  validate_jsons:
    name: Validate jsons
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate json
      - name: json-syntax-check
        uses: limitusus/json-syntax-check@v1
        with:
          pattern: "\\.json$"
